#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors")

console.log(c.clear + c.multi("Welcome to the Dice Program"));

function randInt(min,max) {
  return Math.floor((Math.random() * (max - min + 1)) + min);
}

var total = 0;
for (var n=0; n < 5; n++) {
  var side = randInt(1,6);
  console.log("You rolled a " + side);
  total += side;
}

console.log("Total: " + total)
